<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bc0</string>
	</array>
	<key>name</key>
	<string>BC0</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string># (int pool count|int pool|string pool total size|string pool|function count|function_pool|native count|native pool)</string>
			<key>name</key>
			<string>comment.description.bc0</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#&lt;([a-zA-Z0-9]*)&gt;</string>
			<key>name</key>
			<string>comment.function.name.bc0</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_innards</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$(
?)</string>
			<key>name</key>
			<string>comment.line.bc0</string>
		</dict>
		<key>function_innards</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\snumber\sof\sarguments\s=\s[0-9]+</string>
					<key>name</key>
					<string>comment.function.description.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\snumber\sof\slocal\svariables\s=\s[0-9]+</string>
					<key>name</key>
					<string>comment.function.description.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\scode\slength\s=\s[0-9]+\sbytes</string>
					<key>name</key>
					<string>comment.function.description.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s(new|newarray|aaddf|ildc|aldc|vstore|vload|invokenative|invokestatic)\s[0-9]+</string>
					<key>name</key>
					<string>comment.instruction.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s(bipush|goto|if_icmplt|if_icmple|if_icmpgt|if_icmpge|if_cmpeq|if_cmpne|goto)\s([+-]?)[0-9]+</string>
					<key>name</key>
					<string>comment.instruction.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s(dup|pop|swap|iadd|iand|idiv|imul|ior|irem|ishl|ishr|isub|ixor|athrow|assert|aconst_null|nop|arraylength|aadds|cmload|cmstore|amload|amstore|imload|imstore|return)\s</string>
					<key>name</key>
					<string>comment.instruction.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s(addrof_static|addrof_native|addtag)\s[0-9]+</string>
					<key>name</key>
					<string>comment.instruction.bc0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s(invokedynamic|hastag|checktag)\s</string>
					<key>name</key>
					<string>comment.instruction.bc0</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bc0</string>
	<key>uuid</key>
	<string>B49A4B2B-DE5D-4770-A913-ED59020110FC</string>
</dict>
</plist>
