<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>clac</string>
	</array>
	<key>name</key>
	<string>Clac</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword_tokens</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_tokens</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>:([\s]*)(comment)</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.clac</string>
		</dict>
		<key>keyword_tokens</key>
		<dict>
			<key>match</key>
			<string>(drop|pick|swap|rot|print|quit|if|skip)</string>
			<key>name</key>
			<string>keyword.defined.token.clac</string>
		</dict>
		<key>line</key>
		<dict>
			<key>begin</key>
			<string>(:)([\s]*)([\S]*)([\s]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.statement.clac</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clac</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.clac</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_tokens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_tokens</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)\.?\d(?:(?:[0-9a-zA-Z_\.]|'))*</string>
			<key>name</key>
			<string>constant.numeric.clac</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%|\*|/|-|\+|\*\*</string>
					<key>name</key>
					<string>keyword.operator.clac</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.clac</string>
				</dict>
			</array>
		</dict>
		<key>other_tokens</key>
		<dict>
			<key>match</key>
			<string>(\b)([\S]+)(\s)</string>
			<key>name</key>
			<string>keyword.other.token.clac</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.clac</string>
	<key>uuid</key>
	<string>4487548F-9F2B-4084-B8E6-998CECEEB513</string>
</dict>
</plist>
